
// --------------------------------------------------------------------------------------------------
//	This code was generated by the ETLA Toolbelt Wizard version 1.0.59.11
//	Generated date: 2021-Mar-04 16:30:31
//
//	Changes to this file will be lost if the code is regenerated.
//	To make changes or additions, rerun the ETLA Toolbelt Wizard after editing T4 templates if required
// </auto-generated>
// --------------------------------------------------------------------------------------------------

using Microsoft.VisualBasic.Logging;

namespace EtlaToolboxPicker.EtlaToolbelt.Logs;

/// <summary>Defines the various elements of a log message (not just its text), e.g. when the message was created</summary>
public class LogMessage
{
    /// <summary>Provides a version number for the LogMessage structure being used
    /// This allows for changes to the structure and allows sinks to work out if they can handle a message
    /// </summary>
    public int? Version = 1;  // Change this if this class is amended so we can handle version changes

    /// <summary>What sort of message this is
    /// This allows sinks to ignore messages they are not interested in
    /// </summary>
    public LogLevel Level { get; set; }

    /// <summary>The text of the log message</summary>
    public string? Msg { get; set; } = "";

    /// <summary>An exception related to the log message (if any)</summary>
    internal Exception? E { get; set; }

    /// <summary>The text of a related exception (if any)</summary>
    public string Ex { get; set; } = "";

    /// <summary> When the log message was created</summary>
    public DateTime? Stamp { get; set; } = DateTime.Now;

    /// <summary>The method which called the log mechanism</summary>
    public string? Caller { get; set; } = "";

    /// <summary>The path of the source code of the method which called the log mechanism</summary>
    public string? Path { get; set; } = "";

    /// <summary>The line number in the source code where the log mechanism was invoked</summary>
    public int? Line { get; set; }

    /// <summary>A unique guid for each log message</summary>
    public Guid? MsgGuid { get; set; }

    /// <summary>A unique guid for this application instance 
    /// useful for sinks such as databases where multiple applications may be writing simultaneously
    /// </summary>
    public Guid? InstanceGuid { get; set; } = Log.Guid;

    /// <summary>A unique guid for this application</summary>
    public Guid? AppGuid { get; set; } = Context.AppGuid;
}

